# Generated by Django 2.2.12 on 2024-03-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_TP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='color',
        ),
    ]
