# Generated by Django 2.2.12 on 2024-03-13 13:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_men', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='smiley1',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='To tournament participant 1 (Woman) '),
        ),
        migrations.AlterField(
            model_name='player',
            name='smiley2',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='To tournament participant 2 (Woman) '),
        ),
        migrations.AlterField(
            model_name='player',
            name='smiley3',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='To tournament participant 3 (Woman) '),
        ),
        migrations.AlterField(
            model_name='player',
            name='smiley4',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='To tournament participant 4 (Man)  '),
        ),
        migrations.AlterField(
            model_name='player',
            name='smiley5',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='To tournament participant 5 (Man)  '),
        ),
        migrations.AlterField(
            model_name='player',
            name='smiley6',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='To tournament participant 6 (Man)  '),
        ),
    ]
